import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { ToastProvider } from "@/components/ui/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const GOOGLE_MAPS_KEY = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY || "";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ToastProvider>{children}</ToastProvider>
        {GOOGLE_MAPS_KEY && (
          <Script
            id="google-maps-places"
            src={`https://maps.googleapis.com/maps/api/js?key=${GOOGLE_MAPS_KEY}&libraries=places&loading=async`}
            strategy="afterInteractive"
            onLoad={() => {
              if (typeof window !== "undefined") {
                (window as any).__GOOGLE_MAPS_LOADED__ = true;
                window.dispatchEvent(new Event("google-maps-loaded"));
              }
            }}
            onError={() => {
              if (typeof window !== "undefined") {
                (window as any).__GOOGLE_MAPS_ERROR__ = true;
                window.dispatchEvent(new Event("google-maps-error"));
              }
            }}
          />
        )}
      </body>
    </html>
  );
}